### ISSUE TITLE
crashes when item is added

### ISSUE THREAD

**Issue by ingenthr** [avsej/couchbase-kafka-hadoop-demo#1]
Start the producer connected to an empty bucket.  In the UI, click on documents -> add document.  Watch it crash.
# java -cp couchbase-kafka-hadoop-demo-1.0-all.jar:. example.Cl

ickStreamProducer
INFO - Starting ZkClient event thread.
226 [main] INFO org.apache.zookeeper.ZooKeeper - Client environment:zookeeper.version=3.4.6-1569965, built on 02/20/2014 09:09 GMT
226 [main] INFO org.apache.zookeeper.ZooKeeper - Client environment:host.name=sandbox.hortonworks.com
227 [main] INFO org.apache.zookeeper.ZooKeeper - Client environment:java.version=1.7.0_71
227 [main] INFO org.apache.zookeeper.ZooKeeper - Client environment:java.vendor=Oracle Corporation
227 [main] INFO org.apache.zookeeper.ZooKeeper - Client environment:java.home=/usr/lib/jvm/java-1.7.0-openjdk-1.7.0.71.x86_64/jre
227 [main] INFO org.apache.zookeeper.ZooKeeper - Client environment:java.class.path=couchbase-kafka-hadoop-demo-1.0-all.jar:.
227 [main] INFO org.apache.zookeeper.ZooKeeper - Client environment:java.library.path=/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
227 [main] INFO org.apache.zookeeper.ZooKeeper - Client environment:java.io.tmpdir=/tmp
227 [main] INFO org.apache.zookeeper.ZooKeeper - Client environment:java.compiler=<NA>
227 [main] INFO org.apache.zookeeper.ZooKeeper - Client environment:os.name=Linux
227 [main] INFO org.apache.zookeeper.ZooKeeper - Client environment:os.arch=amd64
227 [main] INFO org.apache.zookeeper.ZooKeeper - Client environment:os.version=2.6.32-504.1.3.el6.x86_64
227 [main] INFO org.apache.zookeeper.ZooKeeper - Client environment:user.name=root
227 [main] INFO org.apache.zookeeper.ZooKeeper - Client environment:user.home=/root
227 [main] INFO org.apache.zookeeper.ZooKeeper - Client environment:user.dir=/root
229 [main] INFO org.apache.zookeeper.ZooKeeper - Initiating client connection, connectString=localhost:2181 sessionTimeout=4000 watcher=org.I0Itec.zkclient.ZkClient@5c56fa08
253 [main-SendThread(localhost.localdomain:2181)] INFO org.apache.zookeeper.ClientCnxn - Opening socket connection to server localhost.localdomain/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error)
262 [main-SendThread(localhost.localdomain:2181)] INFO org.apache.zookeeper.ClientCnxn - Socket connection established to localhost.localdomain/127.0.0.1:2181, initiating session
272 [main-SendThread(localhost.localdomain:2181)] INFO org.apache.zookeeper.ClientCnxn - Session establishment complete on server localhost.localdomain/127.0.0.1:2181, sessionid = 0x14b850013f30003, negotiated timeout = 4000
INFO - zookeeper state changed (SyncConnected)
INFO - Verifying properties
INFO - Property key.serializer.class is overridden to kafka.serializer.StringEncoder
INFO - Property metadata.broker.list is overridden to 
INFO - Property serializer.class is overridden to kafka.serializer.StringEncoder
817 [main] INFO com.couchbase.client.core.CouchbaseCore - CoreEnvironment: {sslEnabled=false, sslKeystoreFile='null', sslKeystorePassword='null', queryEnabled=false, queryPort=8093, bootstrapHttpEnabled=true, bootstrapCarrierEnabled=true, bootstrapHttpDirectPort=8091, bootstrapHttpSslPort=18091, bootstrapCarrierDirectPort=11210, bootstrapCarrierSslPort=11207, ioPoolSize=2, computationPoolSize=2, responseBufferSize=16384, requestBufferSize=16384, kvServiceEndpoints=1, viewServiceEndpoints=1, queryServiceEndpoints=1, ioPool=NioEventLoopGroup, coreScheduler=CoreScheduler, packageNameAndVersion=couchbase-jvm-core/1.1.0-dp (git: 1.1.0-dp), dcpEnabled=true}
1307 [cb-io-1-1] INFO com.couchbase.client.core.node.Node - Connected to Node localhost
1840 [cb-computations-1] INFO com.couchbase.client.core.config.ConfigurationProvider - Opened bucket default
24330 [cb-computations-2] INFO com.couchbase.kafka.CouchbaseProducer - post document 'mattwashere'
ERROR - fetching topic metadata for topics [Set(default)] from broker [List()] failed
kafka.common.KafkaException: fetching topic metadata for topics [Set(default)] from broker [List()] failed
    at kafka.client.ClientUtils$.fetchTopicMetadata(ClientUtils.scala:67)
    at kafka.producer.BrokerPartitionInfo.updateInfo(BrokerPartitionInfo.scala:82)
    at kafka.producer.async.DefaultEventHandler$$anonfun$handle$1.apply$mcV$sp(DefaultEventHandler.scala:67)
    at kafka.utils.Utils$.swallow(Utils.scala:167)
    at kafka.utils.Logging$class.swallowError(Logging.scala:106)
    at kafka.utils.Utils$.swallowError(Utils.scala:46)
    at kafka.producer.async.DefaultEventHandler.handle(DefaultEventHandler.scala:67)
    at kafka.producer.Producer.send(Producer.scala:76)
    at kafka.javaapi.producer.Producer.send(Producer.scala:33)
    at com.couchbase.kafka.CouchbaseProducer.postMessage(CouchbaseProducer.java:149)
    at com.couchbase.kafka.CouchbaseProducer$1.call(CouchbaseProducer.java:137)
    at com.couchbase.kafka.CouchbaseProducer$1.call(CouchbaseProducer.java:134)
    at rx.observables.BlockingObservable$1.onNext(BlockingObservable.java:123)
    at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:130)
    at rx.internal.operators.OperatorMerge$InnerSubscriber.emit(OperatorMerge.java:620)
    at rx.internal.operators.OperatorMerge$InnerSubscriber.onNext(OperatorMerge.java:545)
    at rx.internal.operators.OperatorMerge$InnerSubscriber.emit(OperatorMerge.java:635)
    at rx.internal.operators.OperatorMerge$InnerSubscriber.onNext(OperatorMerge.java:545)
    at rx.internal.operators.NotificationLite.accept(NotificationLite.java:150)
    at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.pollQueue(OperatorObserveOn.java:189)
    at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.access$000(OperatorObserveOn.java:65)
    at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber$2.call(OperatorObserveOn.java:153)
    at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:47)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
ERROR - Failed to collate messages by topic, partition due to: fetching topic metadata for topics [Set(default)] from broker [List()] failed
INFO - Back off for 100 ms before retrying send. Remaining retries = 3
ERROR - fetching topic metadata for topics [Set(default)] from broker [List()] failed
kafka.common.KafkaException: fetching topic metadata for topics [Set(default)] from broker [List()] failed
    at kafka.client.ClientUtils$.fetchTopicMetadata(ClientUtils.scala:67)
    at kafka.producer.BrokerPartitionInfo.updateInfo(BrokerPartitionInfo.scala:82)
    at kafka.producer.async.DefaultEventHandler$$anonfun$handle$2.apply$mcV$sp(DefaultEventHandler.scala:78)
    at kafka.utils.Utils$.swallow(Utils.scala:167)
    at kafka.utils.Logging$class.swallowError(Logging.scala:106)
    at kafka.utils.Utils$.swallowError(Utils.scala:46)
    at kafka.producer.async.DefaultEventHandler.handle(DefaultEventHandler.scala:78)
    at kafka.producer.Producer.send(Producer.scala:76)
    at kafka.javaapi.producer.Producer.send(Producer.scala:33)
    at com.couchbase.kafka.CouchbaseProducer.postMessage(CouchbaseProducer.java:149)
    at com.couchbase.kafka.CouchbaseProducer$1.call(CouchbaseProducer.java:137)
    at com.couchbase.kafka.CouchbaseProducer$1.call(CouchbaseProducer.java:134)
    at rx.observables.BlockingObservable$1.onNext(BlockingObservable.java:123)
    at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:130)
    at rx.internal.operators.OperatorMerge$InnerSubscriber.emit(OperatorMerge.java:620)
    at rx.internal.operators.OperatorMerge$InnerSubscriber.onNext(OperatorMerge.java:545)
    at rx.internal.operators.OperatorMerge$InnerSubscriber.emit(OperatorMerge.java:635)
    at rx.internal.operators.OperatorMerge$InnerSubscriber.onNext(OperatorMerge.java:545)
    at rx.internal.operators.NotificationLite.accept(NotificationLite.java:150)
    at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.pollQueue(OperatorObserveOn.java:189)
    at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.access$000(OperatorObserveOn.java:65)
    at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber$2.call(OperatorObserveOn.java:153)
    at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:47)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
ERROR - Failed to collate messages by topic, partition due to: fetching topic metadata for topics [Set(default)] from broker [List()] failed
INFO - Back off for 100 ms before retrying send. Remaining retries = 2
ERROR - fetching topic metadata for topics [Set(default)] from broker [List()] failed
kafka.common.KafkaException: fetching topic metadata for topics [Set(default)] from broker [List()] failed
    at kafka.client.ClientUtils$.fetchTopicMetadata(ClientUtils.scala:67)
    at kafka.producer.BrokerPartitionInfo.updateInfo(BrokerPartitionInfo.scala:82)
    at kafka.producer.async.DefaultEventHandler$$anonfun$handle$2.apply$mcV$sp(DefaultEventHandler.scala:78)
    at kafka.utils.Utils$.swallow(Utils.scala:167)
    at kafka.utils.Logging$class.swallowError(Logging.scala:106)
    at kafka.utils.Utils$.swallowError(Utils.scala:46)
    at kafka.producer.async.DefaultEventHandler.handle(DefaultEventHandler.scala:78)
    at kafka.producer.Producer.send(Producer.scala:76)
    at kafka.javaapi.producer.Producer.send(Producer.scala:33)
    at com.couchbase.kafka.CouchbaseProducer.postMessage(CouchbaseProducer.java:149)
    at com.couchbase.kafka.CouchbaseProducer$1.call(CouchbaseProducer.java:137)
    at com.couchbase.kafka.CouchbaseProducer$1.call(CouchbaseProducer.java:134)
    at rx.observables.BlockingObservable$1.onNext(BlockingObservable.java:123)
    at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:130)
    at rx.internal.operators.OperatorMerge$InnerSubscriber.emit(OperatorMerge.java:620)
    at rx.internal.operators.OperatorMerge$InnerSubscriber.onNext(OperatorMerge.java:545)
    at rx.internal.operators.OperatorMerge$InnerSubscriber.emit(OperatorMerge.java:635)
    at rx.internal.operators.OperatorMerge$InnerSubscriber.onNext(OperatorMerge.java:545)
    at rx.internal.operators.NotificationLite.accept(NotificationLite.java:150)
    at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.pollQueue(OperatorObserveOn.java:189)
    at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.access$000(OperatorObserveOn.java:65)
    at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber$2.call(OperatorObserveOn.java:153)
    at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:47)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
ERROR - Failed to collate messages by topic, partition due to: fetching topic metadata for topics [Set(default)] from broker [List()] failed
INFO - Back off for 100 ms before retrying send. Remaining retries = 1
ERROR - fetching topic metadata for topics [Set(default)] from broker [List()] failed
kafka.common.KafkaException: fetching topic metadata for topics [Set(default)] from broker [List()] failed
    at kafka.client.ClientUtils$.fetchTopicMetadata(ClientUtils.scala:67)
    at kafka.producer.BrokerPartitionInfo.updateInfo(BrokerPartitionInfo.scala:82)
    at kafka.producer.async.DefaultEventHandler$$anonfun$handle$2.apply$mcV$sp(DefaultEventHandler.scala:78)
    at kafka.utils.Utils$.swallow(Utils.scala:167)
    at kafka.utils.Logging$class.swallowError(Logging.scala:106)
    at kafka.utils.Utils$.swallowError(Utils.scala:46)
    at kafka.producer.async.DefaultEventHandler.handle(DefaultEventHandler.scala:78)
    at kafka.producer.Producer.send(Producer.scala:76)
    at kafka.javaapi.producer.Producer.send(Producer.scala:33)
    at com.couchbase.kafka.CouchbaseProducer.postMessage(CouchbaseProducer.java:149)
    at com.couchbase.kafka.CouchbaseProducer$1.call(CouchbaseProducer.java:137)
    at com.couchbase.kafka.CouchbaseProducer$1.call(CouchbaseProducer.java:134)
    at rx.observables.BlockingObservable$1.onNext(BlockingObservable.java:123)
    at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:130)
    at rx.internal.operators.OperatorMerge$InnerSubscriber.emit(OperatorMerge.java:620)
    at rx.internal.operators.OperatorMerge$InnerSubscriber.onNext(OperatorMerge.java:545)
    at rx.internal.operators.OperatorMerge$InnerSubscriber.emit(OperatorMerge.java:635)
    at rx.internal.operators.OperatorMerge$InnerSubscriber.onNext(OperatorMerge.java:545)
    at rx.internal.operators.NotificationLite.accept(NotificationLite.java:150)
    at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.pollQueue(OperatorObserveOn.java:189)
    at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.access$000(OperatorObserveOn.java:65)
    at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber$2.call(OperatorObserveOn.java:153)
    at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:47)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
ERROR - Failed to collate messages by topic, partition due to: fetching topic metadata for topics [Set(default)] from broker [List()] failed
INFO - Back off for 100 ms before retrying send. Remaining retries = 0
ERROR - fetching topic metadata for topics [Set(default)] from broker [List()] failed
kafka.common.KafkaException: fetching topic metadata for topics [Set(default)] from broker [List()] failed
    at kafka.client.ClientUtils$.fetchTopicMetadata(ClientUtils.scala:67)
    at kafka.producer.BrokerPartitionInfo.updateInfo(BrokerPartitionInfo.scala:82)
    at kafka.producer.async.DefaultEventHandler$$anonfun$handle$2.apply$mcV$sp(DefaultEventHandler.scala:78)
    at kafka.utils.Utils$.swallow(Utils.scala:167)
    at kafka.utils.Logging$class.swallowError(Logging.scala:106)
    at kafka.utils.Utils$.swallowError(Utils.scala:46)
    at kafka.producer.async.DefaultEventHandler.handle(DefaultEventHandler.scala:78)
    at kafka.producer.Producer.send(Producer.scala:76)
    at kafka.javaapi.producer.Producer.send(Producer.scala:33)
    at com.couchbase.kafka.CouchbaseProducer.postMessage(CouchbaseProducer.java:149)
    at com.couchbase.kafka.CouchbaseProducer$1.call(CouchbaseProducer.java:137)
    at com.couchbase.kafka.CouchbaseProducer$1.call(CouchbaseProducer.java:134)
    at rx.observables.BlockingObservable$1.onNext(BlockingObservable.java:123)
    at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:130)
    at rx.internal.operators.OperatorMerge$InnerSubscriber.emit(OperatorMerge.java:620)
    at rx.internal.operators.OperatorMerge$InnerSubscriber.onNext(OperatorMerge.java:545)
    at rx.internal.operators.OperatorMerge$InnerSubscriber.emit(OperatorMerge.java:635)
    at rx.internal.operators.OperatorMerge$InnerSubscriber.onNext(OperatorMerge.java:545)
    at rx.internal.operators.NotificationLite.accept(NotificationLite.java:150)
    at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.pollQueue(OperatorObserveOn.java:189)
    at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.access$000(OperatorObserveOn.java:65)
    at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber$2.call(OperatorObserveOn.java:153)
    at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:47)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
ERROR - Failed to send requests for topics default with correlation ids in [0,8]
Exception in thread "main" kafka.common.FailedToSendMessageException: Failed to send messages after 3 tries.
    at kafka.producer.async.DefaultEventHandler.handle(DefaultEventHandler.scala:90)
    at kafka.producer.Producer.send(Producer.scala:76)
    at kafka.javaapi.producer.Producer.send(Producer.scala:33)
    at com.couchbase.kafka.CouchbaseProducer.postMessage(CouchbaseProducer.java:149)
    at com.couchbase.kafka.CouchbaseProducer$1.call(CouchbaseProducer.java:137)
    at com.couchbase.kafka.CouchbaseProducer$1.call(CouchbaseProducer.java:134)
    at rx.observables.BlockingObservable$1.onNext(BlockingObservable.java:123)
    at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:130)
    at rx.internal.operators.OperatorMerge$InnerSubscriber.emit(OperatorMerge.java:620)
    at rx.internal.operators.OperatorMerge$InnerSubscriber.onNext(OperatorMerge.java:545)
    at rx.internal.operators.OperatorMerge$InnerSubscriber.emit(OperatorMerge.java:635)
    at rx.internal.operators.OperatorMerge$InnerSubscriber.onNext(OperatorMerge.java:545)
    at rx.internal.operators.NotificationLite.accept(NotificationLite.java:150)
    at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.pollQueue(OperatorObserveOn.java:189)
    at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.access$000(OperatorObserveOn.java:65)
    at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber$2.call(OperatorObserveOn.java:153)
    at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:47)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)

**Comment by ingenthr** [comment]
I think this is resolved as I found Kafka wasn't running properly.  After I fixed that it worked on the 3rd try or so.

The second try failed with this:
4230 [main] INFO com.couchbase.kafka.CouchbaseProducer - Found broker: sandbox.hortonworks.com:6667
INFO - Verifying properties
INFO - Property key.serializer.class is overridden to kafka.serializer.StringEncoder
INFO - Property metadata.broker.list is overridden to sandbox.hortonworks.com:6667
INFO - Property serializer.class is overridden to kafka.serializer.StringEncoder

4517 [main] INFO com.couchbase.client.core.CouchbaseCore - CoreEnvironment: {sslEnabled=false, sslKeystoreFile='null', sslKeystorePassword='null', queryEnabled=false, queryPort=8093, bootstrapHttpEnabled=true, bootstrapCarrierEnabled=true, bootstrapHttpDirectPort=8091, bootstrapHttpSslPort=18091, bootstrapCarrierDirectPort=11210, bootstrapCarrierSslPort=11207, ioPoolSize=2, computationPoolSize=2, responseBufferSize=16384, requestBufferSize=16384, kvServiceEndpoints=1, viewServiceEndpoints=1, queryServiceEndpoints=1, ioPool=NioEventLoopGroup, coreScheduler=CoreScheduler, packageNameAndVersion=couchbase-jvm-core/1.1.0-dp (git: 1.1.0-dp), dcpEnabled=true}

5966 [cb-io-1-1] INFO com.couchbase.client.core.node.Node - Connected to Node localhost
Exception in thread "main" java.lang.RuntimeException: java.util.concurrent.TimeoutException
    at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:470)
    at rx.observables.BlockingObservable.single(BlockingObservable.java:340)
    at com.couchbase.kafka.CouchbaseProducer.run(CouchbaseProducer.java:116)
    at example.ClickStreamProducer.main(ClickStreamProducer.java:51)
Caused by: java.util.concurrent.TimeoutException
    at rx.internal.operators.OperatorTimeoutBase$TimeoutSubscriber.onTimeout(OperatorTimeoutBase.java:169)
    at rx.internal.operators.OperatorTimeout$1$1.call(OperatorTimeout.java:42)
    at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:47)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
